[theme]
primaryColor = "#3d85c6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f4f7"
textColor = "#101828"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
